cask_args appdir: '/Applications'

tap 'homebrew/services'
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'caskroom/fonts'
tap 'jhawthorn/fzy'
tap 'neovim/neovim'
tap 'homebrew/homebrew-php'

## CLI

brew 'git'
brew 'libgit2'
brew 'the_silver_searcher'
brew 'postgresql'
brew 'mysql'
brew 'redis'
brew 'phantomjs'
brew 'hub'
brew 'vim'
brew 'neovim'
brew 'ctags'
brew 'tmux'
brew 'htop'
brew 'reattach-to-user-namespace'
brew 'go'
brew 'fortune'
brew 'sl' # Corrects bad typing
brew 'tree'
brew 'yadm'
brew 'mas'
brew 'git-crypt'
brew 'zplug'
brew 'fzy'
brew 'fzf'
brew 'yarn'
brew 'fswatch'
brew 'unison'

## PHP

brew 'php71'
brew 'php71-pdo-pgsql'
brew 'php71-ssh2'
brew 'php71-intl'
brew 'php71-libsodium'
brew 'php71-mcrypt'

## Node

brew 'node'

## Applications

cask 'google-chrome'
cask 'firefox'
cask 'slack'
cask 'iterm2'
cask 'spectacle'
cask 'atom'
cask 'phpstorm'
cask 'dash'
cask 'gpgtools'
cask 'virtualbox'
cask 'vagrant'
cask 'hipchat'
cask 'sequel-pro-nightly'
cask 'postico'
cask 'docker'
cask 'cyberduck'
cask 'postman'
cask 'steam'
cask 'bbedit'

## Fonts

cask 'font-menlo-for-powerline'
cask 'font-monoid-nerd-font'
